name: logistix_driver
description: A Flutter application for Logistix Partner.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sentry_flutter: ^9.8.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  provider: ^6.1.1

  # Network & API
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^6.1.4
  http: ^1.2.0

  # Dependency Injection
  get_it: ^8.0.3

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils
  logger: ^2.0.2+1
  intl: ^0.20.2
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  url_launcher: ^6.2.5
  jwt_decoder: ^2.0.1
  json_annotation: ^4.8.1
  image_picker: ^1.0.7

  # Firebase
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10

  # Notifications
  flutter_local_notifications: ^18.0.1

  # Map & Location
  geolocator: ^14.0.2

dev_dependencies:
  sentry_dart_plugin: ^3.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.10
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - .env
    - assets/images/ 
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: logistix
